name: CreditDefaulterClassification
channels:
  - defaults
  - conda-forge
dependencies:
  - xlrd
  - numpy
  - pandas
  - seaborn
  - scipy
  - statsmodels
  - scikit-learn
  - joblib
  - ipykernel
  - imbalanced-learn
  - tensorflow-gpu
  - jupyterlab